export const types = Object.freeze({
  TASK_START_FETCHING: "TASK_START_FETCHING",
	TASK_STOP_FETCHING: "TASK_STOP_FETCHING",
	TASK_FILL_TASK: "TASK_FILL_TASK",
	TASK_SET_FETCHING_ERROR: "TASK_SET_FETCHING_ERROR",
	TASK_SELECTED_TASK: 'TASK_SELECTED_TASK',
});
